### ISSUE TITLE
RadListView jumping / flickering on load on demand

### ISSUE THREAD

**Issue by ignaciolarranaga** [telerik/nativescript-ui-samples#164] opened 2017-01-30 11:55 UTC
### Tell us about the problem
If you carefully pay attention to the scrolling there is a jump / flick when the page load on demand is loaded.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): (look for the 2.4.0
- Plugin(s): "nativescript-telerik-ui": "next" (because already handling unpublished fixes),

### Please tell us how to recreate the issue in as much detail as possible.
Just scroll with on demand items on iOS

**Comment by imaginationcoder** [comment] 2017-02-04 08:51
+ 1

**Comment by ginev** [comment] 2017-02-07 16:19
Hello @ignaciolarranaga,

Am I understanding it correctly: you notice a small jump while a scroll animation is running and a chunk of data is loaded into the list simultaneously?

**Comment by ignaciolarranaga** [comment] 2017-02-07 17:09
In my case I have a list with images, while scrolling I'm like seeing 3 of them at a time and suddenly the scroll moves and the one that was on the scroll is out of the view, like a sudden jump on the scroll and a little blink (I think that associated to the same).

I think I'll have my app published on a few days, I'll ping back once available for reference if needed.

**Comment by imaginationcoder** [comment] 2017-02-07 19:56
For me it happens every time loadondemand function executed and my listview also showing images along with other data

**Comment by ginev** [comment] 2017-02-08 12:43
@ignaciolarranaga, @imaginationcoder, thanks for the details. I guess with a project to reproduce the issue would be the best way for us to investigate what goes wrong.

**Comment by KoushikJit** [comment] 2017-02-18 15:53
I got the same issue. I have a list where each list item has an image and some 2/3 lines of text under the image. If I scroll down no issue. But after I have scrolled down a bit, if I start scrolling upwards I see the flickering occurs. I think it's because when the list items are out of scope they are "unloaded" and when you scroll up they start to load again. Now the text is loaded fast but the image takes time to load.
So when you scroll up to a list item the text loads first and then the image pops in (on top of the text , inside the list item) and the list items under it is pushed downwards a little bit to cause the flicker.

I wonder if there is any option so that we can stop the list item contents from being unloaded when they go out of scope due to scrolling down. So that when we scroll up the items should be there as they were before.
Also loading the images again due to scroll up will require the same image to be downloaded twice.

**Comment by ignaciolarranaga** [comment] 2017-02-19 12:46
Hey @ginev here the examples:
* https://itunes.apple.com/app/id1090462266
* https://play.google.com/store/apps/details?id=com.hezea.ForSaleByOwnerLite

Slowly scroll down from the top and you will see suddenly the image change.

**Comment by StJoker** [comment] 2017-03-01 18:47
Try add itemHeight 
` <lv:ListViewLinearLayout scrollDirection="Vertical" itemHeight="350" />`

**Comment by ignaciolarranaga** [comment] 2017-03-01 18:51
The height is already fixed actually, here is the code:

<GridLayout>
    <ActivityIndicator [busy]="isLoading" [visibility]="isLoading ? 'visible' : 'collapse'"
        width="50" *ngIf="!dataLoaded"></ActivityIndicator>

    <StackLayout *ngIf="dataLoaded && properties?.length == 0" class="no-properties-found">
        <Image src="res://oops" class="no-properties-found-image"></Image>
        <Label [text]="'main.all-properties.no-properties-found' | translate" textWrap="true"></Label>
    </StackLayout>

    <RadListView #listView [items]="properties" *ngIf="dataLoaded && properties?.length > 0"
        loadOnDemandMode="Auto" (loadMoreDataRequested)="onLoadMoreItemsRequested($event)"
        pullToRefresh="true" (pullToRefreshInitiated)="onPullToRefreshInitiated($event)">
        <template tkListItemTemplate let-item="item" let-index="index">
            <StackLayout>
                <StackLayout class="separator"></StackLayout>
                <property [listPosition]="'all-properties-' + index" [property]="item"></property>
            </StackLayout>
        </template>
        <template tkListViewFooter *ngIf="dataLoaded && !hasMorePages">
            <StackLayout>
                <StackLayout class="separator"></StackLayout>
                <Label [text]="'main.all-properties.footer' | translate" textWrap="true" class="footer"></Label>
            </StackLayout>
        </template>

        <ListViewLinearLayout tkListViewLayout scrollDirection="Vertical" itemInsertAnimation="Default" itemDeleteAnimation="Default"
            itemWidht="100%" itemHeight="250" dynamicItemSize="false"></ListViewLinearLayout>
    </RadListView>
</GridLayout>

**Comment by ginev** [comment] 2017-03-06 11:56
Hello @ignaciolarranaga,

First, sorry for the late reply. 

I cannot say what the reason for the glitchy behavior is. Can you paste the code that you have in the `onLoadMoreItemsRequested` event handler? It seems to me that the list control is entirely reset as soon as the user requests more data using the load-on-demand UX. This should not be the case.

Also, please note that from now one issues related to UI for NativeScript should be submittet in the dedicated repository: https://github.com/telerik/nativescript-ui-feedback.

**Comment by ignaciolarranaga** [comment] 2017-03-06 13:05
Hey, no worries, here is the code:

```
onLoadMoreItemsRequested(args: ListViewEventData) {
        let listView: RadListView = args.object;
        this.getNextPage((page: Page<SearchResult>) => {
            if (page.last) {
                //console.log("It was the last page");
                listView.loadOnDemandMode = ListViewLoadOnDemandMode[ListViewLoadOnDemandMode.None];
            }

            listView.notifyLoadOnDemandFinished();
        });
    }

private getNextPage(callback?: (page: Page<SearchResult>) => void) {
        let nextPage = this.currentPage != null ? this.currentPage + 1 : 0;

        //console.log("Loading next page: " + nextPage);
        this.isLoading = true;
        this._searchService.findAll(nextPage)
            .subscribe(
                page => {
                    if (page.first) {
                        this.properties = new ObservableArray<SearchResult>(page.content);
                    } else {
                        this.properties.push(page.content);
                    }
                    //console.log("Data received: " + JSON.stringify(page.content));

                    this.currentPage = page.number;
                    this.hasMorePages = !page.last;
                    //console.log("Page loaded: " + this.currentPage);

                    this.isLoading = false;
                    this.dataLoaded = true;

                    if (callback) {
                        callback(page);
                    }
                },
                error => this._errorService.handleCommunicationError(error, () => { this.ngOnInit(); })
            );
    }
```

Are you guys going to move the issues from repo ?

**Comment by ginev** [comment] 2017-03-08 16:13
@ignaciolarranaga, thanks for the snippet. Yes, we would like to redirect all NS UI related issues to the github.com/telerik/nativescript-ui-feedback repository as a part of our initiative to speed up issue processing. We also plan to close the issues section here so, please, open any forthcoming issues in the dedicated repository.

Can you also show me the Pull-to-Refresh logic. I think it might be the one causing problems?

**Comment by ignaciolarranaga** [comment] 2017-03-08 20:10
Sure, here is the entire component actually, may be better:

```
import * as application from "application";
import * as platformModule from "platform";

import { Subscription } from "rxjs/Rx";
import { Component, ViewChild, ElementRef, OnDestroy, ChangeDetectorRef } from "@angular/core";
import { Router } from "@angular/router";
import { RadListView, ListViewEventData, ListViewLoadOnDemandMode } from "nativescript-telerik-ui/listview";
import { RadListViewComponent } from "nativescript-telerik-ui/listview/angular";
import { ObservableArray } from "data/observable-array";

import { AppConfig } from "../../../app.config";
import { Page, SearchResult } from "../../../shared/dtos";
import { ErrorService, DialogService, SearchService } from "../../../shared/services";
import { GlobalEventsUtilities, GlobalEvent, navigationHandler } from "../../../shared/util";
import { BaseComponent } from "../../base.component";

@Component({
    moduleId: module.id,
    selector: "all-properties",
    templateUrl: "all-properties.html",
    styleUrls: [ "all-properties-common.css" ]
})
export class AllPropertiesComponent extends BaseComponent implements OnDestroy {

    // Both used by the navigationHandler to recover the scroll on Android
    currentScrollPosition: number = null;
    @ViewChild("listView") listViewComponent: RadListViewComponent;

    private _globalEventsSubscription: Subscription;
    
    currentPage: number;
    hasMorePages: boolean;

    properties: ObservableArray<SearchResult>;

    constructor(
        private _changeDetectorRef: ChangeDetectorRef,
        private _router: Router,
        private _errorService: ErrorService,
        private _dialogService: DialogService,
        private _globalEventsUtilities: GlobalEventsUtilities,
        private _searchService: SearchService) {
        super();
    }

    ngOnInit() {
        this.properties = new ObservableArray<SearchResult>();

        this.getNextPage((page: Page<SearchResult>) => {
            this._changeDetectorRef.detectChanges();
        });

        // Handling the scroll on Android
        if (platformModule.isAndroid) {
            // The navigation happens on the PropertyComponent but the control is here
            this._router.events.subscribe(navigationHandler.bind(this, "all-properties"));
        }

        // Subscribing for refresh on search filter changes
		this._globalEventsSubscription = this._globalEventsUtilities.globalEventEmitter.subscribe((e: GlobalEvent) => {
            switch (e.event) {
                case GlobalEvent.SEARCH_FILTERS_CHANGED:
                    //console.log("Refreshing the properties after search filters changed!");
                    this.reset((page: Page<SearchResult>) => {
                        this._changeDetectorRef.detectChanges();
                    });
                    break;
                case GlobalEvent.PROPERTY_FAVORITE_ADDED:
                    this.properties.forEach((p: SearchResult) => {
                        if (p.id == e.data.id) {
                            p.favorite = true;
                        }
                    });
                    break;
                case GlobalEvent.PROPERTY_FAVORITE_REMOVED:
                    this.properties.forEach((p: SearchResult) => {
                        if (p.id == e.data.id) {
                            p.favorite = false;
                        }
                    });
                    break;
                case GlobalEvent.PROPERTY_CONTACTED:
                    this.properties.forEach((p: SearchResult) => {
                        if (p.id == e.data.id) {
                            p.contacted = true;
                            p.calls = e.data.calls;
                        }
                    });
                    break;
            }
		});

        // On the check properties
        application.on(application.resumeEvent, (args: application.ApplicationEventData) => {
            this.checkProperties();
        });
    }

    ngOnDestroy() {
        this._globalEventsSubscription.unsubscribe();

        // Off the check properties
        application.off(application.resumeEvent);
    }

    onLoadMoreItemsRequested(args: ListViewEventData) {
        let listView: RadListView = args.object;
        this.getNextPage((page: Page<SearchResult>) => {
            if (page.last) {
                //console.log("It was the last page");
                listView.loadOnDemandMode = ListViewLoadOnDemandMode[ListViewLoadOnDemandMode.None];
            }

            listView.notifyLoadOnDemandFinished();
        });
    }

    onPullToRefreshInitiated(args: ListViewEventData) {
        let listView: RadListView = args.object;
        this.reset((page: Page<SearchResult>) => {
            listView.notifyPullToRefreshFinished();
            this._changeDetectorRef.detectChanges();
        });
    }

    private checkProperties() {
        console.log("Checking for new properties");
        this._searchService.findAll(0)
            .subscribe(
                page => {
                    let firstPropertyId = this.properties && this.properties.length > 0 ? this.properties.getItem(0).id : null;
                    if (page.content && page.content.length > 0 && page.content[0].id != firstPropertyId) {
                        this._dialogService.confirmWithKey("main.all-properties.new-properties", 
                            (result: boolean) => {
                                if (result) {
                                    this.properties = new ObservableArray<SearchResult>(page.content);

                                    this.currentPage = page.number;
                                    this.hasMorePages = !page.last;

                                    // Not really necessary
                                    this.isLoading = false;
                                    this.dataLoaded = true;

                                    this._changeDetectorRef.detectChanges();
                                }
                            }
                        );
                    } else {
                        console.log("No new properties where detected.");
                    }
                },
                error => this._errorService.handleCommunicationError(error, () => { this.ngOnInit(); })
            );
    }

    private reset(callback?: (page: Page<SearchResult>) => void) {
        this.dataLoaded = false;
        this.currentPage = null;
        this.hasMorePages = true;

        // Reloading the elements
        this.getNextPage(callback);
    }

    private getNextPage(callback?: (page: Page<SearchResult>) => void) {
        let nextPage = this.currentPage != null ? this.currentPage + 1 : 0;

        //console.log("Loading next page: " + nextPage);
        this.isLoading = true;
        this._searchService.findAll(nextPage)
            .subscribe(
                page => {
                    if (page.first) {
                        this.properties = new ObservableArray<SearchResult>(page.content);
                    } else {
                        this.properties.push(page.content);
                    }
                    //console.log("Data received: " + JSON.stringify(page.content));

                    this.currentPage = page.number;
                    this.hasMorePages = !page.last;
                    //console.log("Page loaded: " + this.currentPage);

                    this.isLoading = false;
                    this.dataLoaded = true;

                    if (callback) {
                        callback(page);
                    }
                },
                error => this._errorService.handleCommunicationError(error, () => { this.ngOnInit(); })
            );
    }

}
```

**Comment by ginev** [comment] 2017-03-09 09:37
@ignaciolarranaga I've been playing with your app on iOS and actually don't see any glitches with Load on Demand. What I see is that you reset the whole list when scrolling up because the Pull-to-Refresh logic is triggered. Normally, Pull-to-Refresh is used to append more items at the beginning of the list as demonstrated here: https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/listview/pull-to-refresh. The way you are applying Pull-to-Refresh makes the list suddenly disappear which is not a gut UX practice. Anyway, we have identified a small issue which degrades performance with RadListView when using a List-Footer and will fix it. This should improve scrolling performance.

**Comment by ignaciolarranaga** [comment] 2017-03-09 12:58
Hi @ginev, thanks for the answer, will fix the pull on request as you suggest.

Regarding the original problem, it is actually the components changing on the load on the demand, scroll slowly and pay attention on the first request for example, you will notice suddenly the images that you were seeing near to the top are replaced by new ones (like if you were jump ahead in the scroll). Actually the entire component is replaced, but the image is the most noticeable thing.
The scroll and list keeps consistent, it is just this "jump".
I think it is because the component reutilization that lost sync with the scroll (like component N should be at Ypx and after recalculate another component takes over), but this is most a guess.

I can prepare a video capture if you prefer.

**Comment by ginev** [comment] 2017-03-09 15:35
@ignaciolarranaga, I have managed to reproduce this behavior. I see items suddenly replaced while scrolling slowly towards the end of the list. 

Looking at your code snippets I cannot say what causes the issue. It will be most helpful if you either isolate the case in a project and send it to me for debugging or directly ZIP your app and let me run it on my side.

Since posting here the source of your app isn't a good idea, you can upload it on Google Cloud or Dropbox and send me a private link per e-mail.

Let me know how it works for you?

**Comment by ginev** [comment] 2017-03-10 14:43
This issue was moved to telerik/nativescript-ui-feedback#115

**Closed by ginev** 2017-03-10 14:43 UTC
