### ISSUE TITLE
RadListView scrolling isn't smooth on iOS

### ISSUE THREAD

**Issue by maknz** [telerik/nativescript-ui-samples#45] opened 2015-12-16 20:13 UTC
We've tried out the RadListView component. On Android, it's pretty smooth, just like a regular list view. On iOS though, it's quite.. janky, the scrolling seems a bit jittery and isn't buttery like you'd expect from native components.

v0.1.3

**Comment by ginev** [comment] 2015-12-17 08:16
Hey @maknz ,
There are some performance optimizations being worked on in the iOS component.
Can you share with us some more information on the scenario you are working on so that we can try to reproduce it on our side and see if we can do something about it?

**Comment by maknz** [comment] 2015-12-17 20:23
@ginev I'll provide you a project to reproduce with in Slack, probably the easiest way :)

We're actually going to move to ListView for now, so this isn't needed for us just now, but hopefully the project to reproduce will be useful for your optimisations.

**Comment by ginev** [comment] 2015-12-18 07:08
Thanks @maknz. Is the performance issue the reason you're not choosing RadListView now or do you have other needs that are not covered by the control?

Thanks!

**Comment by maknz** [comment] 2015-12-18 07:28
Partly the performance issue, but our use case is actually simple enough that the regular ListView covers it. All we'd desire is pull to refresh functionality from the RadListView.




We'd certainly look at migrating to it again when we want to expand the scope of functionality.

**Comment by ginev** [comment] 2016-02-02 07:48
Hello @maknz,

We will be introducing a performence improvement in RadListView for NS with the upcoming release so it will be great if you manage to check it out and see how it works for you.

**Closed by ginev** 2016-02-02 07:49 UTC
Labels: bug
