### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

### ISSUE THREAD

**Issue by Taremeh** [telerik/nativescript-ui-samples#141] opened 2016-11-14 16:51 UTC
It seems that an old issue (https://github.com/telerik/nativescript-ui-samples/issues/14) is recurring again...

TNS version: 2.3.0
Plugin: Only the nativescript-telerik-ui Plugin

```
file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:316:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate
(UIKitApplication:org.nativescript.myapp[0xcf1e][21838]): Service exited due to Segmentation fault: 11
```
Then the app crashes / closes itself. I searched for a solution, but couldn't figure out how to fix it.

The error occurs in the sidedrawer.js file:
`TKSideDrawerDelegateImpl.ObjCProtocols = [TKSideDrawerDelegate];`

The only definition of `[TKSideDrawerDelegate]` I found was in "sidedrawer-ios-map.d.ts":

```
declare class TKSideDrawerDelegate {
    static new(): TKSideDrawerDelegate;
}
```

Somehow, "sidedrawer.js" doesn't import the declaration of `TKSideDrawerDelegate` from "sidedrawer-ios-map.d.ts" correctly. Unfortunately I can't fix it...

As I mentioned (https://github.com/telerik/nativescript-ui-samples/issues/14), multiple users are getting the same error. (By the way: The android version works). 

Hopefully, someone can fix it...

**Comment by justinrassier** [comment] 2016-11-20 16:25
This is also happening for me as well. I have tried updating to the latest version of nativescript cli as well as re-adding the ios platform, but still no luck

**Comment by RooFi07** [comment] 2016-11-28 17:25
Do you have any workaround for this? I have the same problem...

**Comment by patrickpereira** [comment] 2016-11-29 11:59
+1

**Comment by VladimirAmiorkov** [comment] 2016-12-05 15:04
Hi,

Are you still experiencing such issues with the latest version:

```
"tns-core-modules": "2.4.0",
"nativescript-telerik-ui-pro": "1.5.1"
```

We are not able to reproduce this issue in a fresh and our Angular and non Angular sdk example project [here](https://github.com/telerik/nativescript-ui-samples-angular) and [here](https://github.com/telerik/nativescript-ui-samples).

Can you try out those project and let me know if the issue is present for you in them. Also if you can provide a sample project that reproduces this issue it would be very helpful.

**Comment by clarenceh** [comment] 2016-12-06 04:07
Hi all,

I spent quite some time and finally get it work by using the following steps (in my project folder):
* tns platform clean ios
* rm -rf node_modules lib platforms
* tns plugin add nativescript-telerik-ui
* Modify app.module.ts and add the nativescript-telerik-ui directives respectively
* In iOS emulator, delete the existing app (I found this is critical)
* tns livesync ios --emulator --watch

I found the critical step seems to first delete the app manually on iOS emulator after the plugin was added.

Hope this help
Clarence

**Comment by VladimirAmiorkov** [comment] 2016-12-06 08:12
@clarenceh Thank you for sharing your findings. This is indeed the way to fully clear the application, unfortunately this is a strange case and we are not sure what exactly is the cause of it. As you mentioned deleting the app from the simulator is crucial in resolving the issue and it looks like there may be some bug in the native simulators.

**Closed** 2016-12-06 08:12 UTC
Labels: needs more info

**Comment by marianedu** [comment] 2017-02-22 07:32
And that seems to be back with tns 2.4.2, nativescript-telerik-ui v 1.6.0

tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:369:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

**Comment by VladimirAmiorkov** [comment] 2017-02-23 08:04
Hi @marianedu have you tried [the approach](https://github.com/telerik/nativescript-ui-samples/issues/141#issuecomment-265055393) @clarenceh wrote about?
