### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by BitsOnCoffee** [telerik/nativescript-ui-samples#110] opened 2016-07-25 16:06 UTC
When installing:

_npm install nativescript-telerik-ui --save_ I get this:

**npm ERR! cb() never called!**

NPM is updated right now..

Any ideas?

**Comment by Natalia-Hristova** [comment] 2017-03-09 08:33
Hello @BitsOnCoffee , 

I can't reproduce it and I'll close it because this repository is only for examples.

If you still face it or have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!

**Closed by Natalia-Hristova** 2017-03-09 08:33 UTC
