### ISSUE TITLE
SideDrawer "overlays app" (on Android only) making it untouchable when opened/closed programmatically

### ISSUE THREAD

**Issue by dragGH102** [telerik/nativescript-ui-samples#52] opened 2016-01-23 19:41 UTC
In my Nativescript app I want the menu to be opened and closed when the user clicks on certain buttons.

However when I programmatically trigger drawer's open (first action)/close (second action) I have the following issue: **after closing the menu (with a button from inside the menu itself), all the area covered by the menu after opening it, it's not touchable anymore** (scroll still works for ScrollView but no tap event).

I played with it for some time and turns out that the reason why the app doesn't allow any more interaction (except for scrolling which is probably "independent" from the specific touch point) is that **RadSideDrawer.drawerContent area is still there, even though invisible and therefore overlays the app itself**
I found out this because I have a few tappable labels in the menu and when I click where they are (on menu open) the tap is triggered as well after closing the menu programmatically.

I created a simple project to show the issue:
https://github.com/dragGH102/nativescript-sample-app-with-menu (sorry for the esthetics :) )

How to reproduce (the issue is on Android only: both emulator and real device):
- click on "open menu" button
- click on menu _ button 3 (or another one). it prints to console: click on label 3
- once the menu (i.e. the drawer) is open, click on "close menu" button (for some reason the button is not shown on Android but it's just below last button "menu_button 4" and it's clickable resulting in closing the menu
- try to click any button in the view: each button is supposed to print "click on **button** 1/2/.." but it doesn't. It prints **label** 1/2/... instead confirming that the menu is still there somehow even though it's hidden. This issue doesn't occur on iOS

Furthermore the **drawerLocation setting seems to have no effect** (I'm not sure whether this has to do with the issue since it seems working in the demo app from this repo) as the menu comes from top).

Thanks in advance

**Comment by dragGH102** [comment] 2016-01-28 18:22
I updated the issue's content with a link to a sample project and how to reproduce the issue (on Android)

**Comment by karaahmed** [comment] 2016-01-29 08:25
Hi dragGH102
Thank you for the project. I've reproduced the issue and will debug it to see what's going on... stay tuned

**Comment by karaahmed** [comment] 2016-01-29 09:33
@dragGH102 
So, the issue is localized in native sidedrawer component for Android and is reproducible only with FadeTransition. Luckily this is fixed with latest Q1 build and we will upload the latest binaries with updated 0.2.4 plugin in a week or two. Meanwhile you can use any one of the other transition types during development. Are you OK with this?

**Comment by dragGH102** [comment] 2016-01-29 12:02
@karaahmed thanks for your answer. It should not be an issue. I will try and I will confirm whether it works for me.

In the meantime, I have one doubt about this specific component's licence: as far as I read from Nativescript blog from which I discovered nativescript-telerik-ui this component is free, so I wanted to understand **whether it will always free and, if not, whether the previous versions (0.23, 0.24 etc.) will still be freely usable and if an attribution is required.**.
Feel free to move my further question to a new issue or elsewhere if appropriate.

Thank you

**Comment by ginev** [comment] 2016-01-29 12:36
Hello @dragGH102 ,
The SideDrawer will always be free :)

**Comment by dragGH102** [comment] 2016-01-29 13:00
@ginev thanks
@karaahmed I confirm the issue is only with **fade** effect.
However with **reveal** and **push** effect the drawer's content appears empty (not sure whether it's my specific case). WIth **reverse** effect it works both open-close-open as well as showing drawer's content. I didn't try the other effects

**Comment by ginev** [comment] 2016-02-02 07:48
Hello @dragGH102 ,
"However with reveal and push effect the drawer's content appears empty (not sure whether it's my specific case). "

I am not able to reproduce this behavior. Can you please try setting `backgroundColor` to the root element of your `mainContent`?

**Comment by dragGH102** [comment] 2016-02-04 23:27
> I am not able to reproduce this behavior. Can you please try setting backgroundColor to the root element of your mainContent?

@ginev Actually I tried to reproduce it in the example project provided.
However it actually works (my bad). But in my specific project (more complex) doesn't. So probably not a {N} bug

**Comment by ginev** [comment] 2016-02-08 08:23
Okay @dragGH102 ,

I am closing this issue.

**Closed by ginev** 2016-02-08 08:23 UTC
