### ISSUE TITLE
Module 'ui/rad-list-view' not found for element 'RadListView'

### ISSUE THREAD

**Issue by dragGH102** [telerik/nativescript-ui-samples#51] opened 2016-01-19 14:26 UTC
As the title states, when I deploy my app after adding telerik-nativescript-ui and a ListView the view shows this error (including the stake trace as reported below).

With all nativescript UI core components (Nativescript 1.5.1 - **tns doctor: all fine**) no problem at all.
I'm deploying on Android (installed sdk tools: 24, build tools: 22+23+24, platform 17+....+23) on Linux (Debian 8)

I also tried **removing and re-adding android platform** to my project.

Here is my view's XML (as explained at http://docs.telerik.com/devtools/nativescript-ui/Controls/ListView/listview-getting-started):

      <Page loaded="loaded" xmlns:lv="nativescript-telerik-ui/listview" xmlns="http://www.nativescript.org/tns.xsd">
             <RadListView>
            </RadListView>
      </Page>

and the corresponding .ts file

    var observableModule = require("data/observable");
    var myViewModel = require("../../shared/view-models/view-model-one");
    var myViewModelInstance = new myViewModel([]);

    var page;
     
    var pageData = new observableModule.Observable({
        items: myViewModelInstance
    });

    exports.loaded = function(args) {
        // binding context
        page = args.object;
        page.bindingContext = pageData;

        // populate list
        myViewModelInstance.empty();
        myViewModelInstance.load();
    };

**Stack trace**: 

          java.lang.RuntimeException: Unable to start activity   
          ComponentInfo{com.company.myApp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
         Calling js method getActivity failed

        Error: Building UI from XML. @file:///app/views/myView/myView.xml:2:5
        Module 'ui/rad-list-view' not found for element 'RadListView'.
        com.tns.NativeScriptException: Failed to find module: "ui/rad-list-view", relative to: /app/tns_modules/
              com.tns.Module.resolvePathHelper(Module.java:197)
            com.tns.Module.resolvePath(Module.java:62)
            com.tns.NativeScriptActivity.getMethodOverrides(Native Method)
            com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:1567)
            android.app.Activity.performCreate(Activity.java:5990)
            android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            android.app.ActivityThread.access$80

**Comment by dragGH102** [comment] 2016-01-19 15:13
I also tried to run the same code after cloning this repository.

The starting view (with the list of various views, examples etc.) opens correctly but, for example, when I click on listView -> grid, I get the very same error

**Comment by ginev** [comment] 2016-01-19 16:36
Hello @dragGH102 ,

I've just tried to reproduce the error you're describing without success. I am using NativeScript 1.5.2 though. Could you please try updating to see if this addresses the case?

What I am doing is:

1. tns create MyTestApp
2. tns plugin add nativescript-telerik-ui
3. Open main-page.xml and add the code above.
4. Run the app.

This works as expected for me.

**Comment by dragGH102** [comment] 2016-01-19 18:16
@ginev thanks for the answer.
however no way

I did:
- upgrade Nativescript to 1.2 including runtimes (procedure at: http://docs.nativescript.org/releases/upgrade-instructions)
- replicated your instructions exactly

Very same error (only the name of the app and xml file change in the stacktrace).
Any other way to structure the xml (i.e. use ListView without any additional xml markup as if I was using Nativescript's ListView) which could perhaps solve my issue?

**Comment by dragGH102** [comment] 2016-01-19 21:20
Apparently there is some issue with my machine.
I tried to make it work on another machine running Os X (sitll deploy to Android) and worked

**Comment by dragGH102** [comment] 2016-01-20 14:31
@ginev sorry to re-open this. 
despite it works on the Os X machine, it is not my primary development machine and it's a pity discarding telerick UI just for a bug anywhere.
Could you please tell me what's your set up? (node and npm versions, OS, emulator/device sdk version, target sdk + output of **npm ls** at least for tns core and telerick nativescript ui)?

thank you in advance

**Comment by ginev** [comment] 2016-01-21 11:26
Hello @dragGH102 
- tns --version prints 1.5.2
- npm --version prints 2.14.7
- android list (list of installed SDKs):
`Available Android targets:
----------
id: 1 or "android-17"
     Name: Android 4.2.2
     Type: Platform
     API level: 17
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 2 or "android-19"
     Name: Android 4.4.2
     Type: Platform
     API level: 19
     Revision: 4
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 3 or "android-22"
     Name: Android 5.1.1
     Type: Platform
     API level: 22
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 4 or "android-MNC"
     Name: Android M (Preview)
     Type: Platform
     API level: MNC
     Revision: 1
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 5 or "android-23"
     Name: Android 6.0
     Type: Platform
     API level: 23
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 6 or "Google Inc.:Google APIs:22"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 5.1.1 (API level 22)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : google_apis/x86
Available Android Virtual Devices:
    Name: Nexus_5_API_22_x86
  Device: Nexus 5 (Google)
    Path: /Users/ginev/.android/avd/Nexus_5_API_22_x86.avd
  Target: Google APIs (Google Inc.)
          Based on Android 5.1.1 (API level 22)
 Tag/ABI: google_apis/x86
    Skin: nexus_5
  Sdcard: 200M
Snapshot: no
Available devices definitions:
id: 0 or "tv_1080p"
    Name: Android TV (1080p)
    OEM : Google
    Tag : android-tv
---------
id: 1 or "tv_720p"
    Name: Android TV (720p)
    OEM : Google
    Tag : android-tv
---------
id: 2 or "wear_round"
    Name: Android Wear Round
    OEM : Google
    Tag : android-wear
---------
id: 3 or "wear_round_chin_320_290"
    Name: Android Wear Round Chin
    OEM : Google
    Tag : android-wear
---------
id: 4 or "wear_square"
    Name: Android Wear Square
    OEM : Google
    Tag : android-wear
---------
id: 5 or "Galaxy Nexus"
    Name: Galaxy Nexus
    OEM : Google
---------
id: 6 or "Nexus 10"
    Name: Nexus 10
    OEM : Google
---------
id: 7 or "Nexus 4"
    Name: Nexus 4
    OEM : Google
---------
id: 8 or "Nexus 5"
    Name: Nexus 5
    OEM : Google
---------
id: 9 or "Nexus 6"
    Name: Nexus 6
    OEM : Google
---------
id: 10 or "Nexus 7 2013"
    Name: Nexus 7
    OEM : Google
---------
id: 11 or "Nexus 7"
    Name: Nexus 7 (2012)
    OEM : Google
---------
id: 12 or "Nexus 9"
    Name: Nexus 9
    OEM : Google
---------
id: 13 or "Nexus One"
    Name: Nexus One
    OEM : Google
---------
id: 14 or "Nexus S"
    Name: Nexus S
    OEM : Google
---------
id: 15 or "2.7in QVGA"
    Name: 2.7" QVGA
    OEM : Generic
---------
id: 16 or "2.7in QVGA slider"
    Name: 2.7" QVGA slider
    OEM : Generic
---------
id: 17 or "3.2in HVGA slider (ADP1)"
    Name: 3.2" HVGA slider (ADP1)
    OEM : Generic
---------
id: 18 or "3.2in QVGA (ADP2)"
    Name: 3.2" QVGA (ADP2)
    OEM : Generic
---------
id: 19 or "3.3in WQVGA"
    Name: 3.3" WQVGA
    OEM : Generic
---------
id: 20 or "3.4in WQVGA"
    Name: 3.4" WQVGA
    OEM : Generic
---------
id: 21 or "3.7 FWVGA slider"
    Name: 3.7" FWVGA slider
    OEM : Generic
---------
id: 22 or "3.7in WVGA (Nexus One)"
    Name: 3.7" WVGA (Nexus One)
    OEM : Generic
---------
id: 23 or "4in WVGA (Nexus S)"
    Name: 4" WVGA (Nexus S)
    OEM : Generic
---------
id: 24 or "4.65in 720p (Galaxy Nexus)"
    Name: 4.65" 720p (Galaxy Nexus)
    OEM : Generic
---------
id: 25 or "4.7in WXGA"
    Name: 4.7" WXGA
    OEM : Generic
---------
id: 26 or "5.1in WVGA"
    Name: 5.1" WVGA
    OEM : Generic
---------
id: 27 or "5.4in FWVGA"
    Name: 5.4" FWVGA
    OEM : Generic
---------
id: 28 or "7in WSVGA (Tablet)"
    Name: 7" WSVGA (Tablet)
    OEM : Generic
---------
id: 29 or "10.1in WXGA (Tablet)"
    Name: 10.1" WXGA (Tablet)
    OEM : Generic
`
- telerik ui is 0.2.3

Testing on Mac OS X El Capitan.

I hope this is helpful.

**Comment by Ivshti** [comment] 2016-01-25 17:58
I have the same issue, on OS X Yosemite with TNS 1.5.2

Any workarounds @ginev  @dragGH102 ?

**Comment by dragGH102** [comment] 2016-01-25 21:02
Hi @Ivo,

personally I left it as it was a trial component anyhow.
But with your configuration it was working to me (on OS X).

Perhaps try to remove and readd ios platform and/or run both on emulator
and real device

On Mon, Jan 25, 2016 at 6:58 PM, Ivo Georgiev <notifications@github.com>
wrote:

> I have the same issue, on OS X Yosemite with TNS 1.5.2
>
> Any workarounds @ginev <https://github.com/ginev> @dragGH102
> <https://github.com/dragGH102> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telerik/nativescript-ui-samples/issues/51#issuecomment-174603637>
> .
>



-- 
*Manuel Gajo*
Full-stack web Developer and Business Designer
*www.manuelgajo.me <http://www.manuelgajo.me>*
+39 333 623 4217 / +32 484 369 265

*IMPORTANT*: My e-mail is personal and PRIVATE and CAN'T be shared with any
third party company or organisation without my explicit authorisation.

**Comment by Ivshti** [comment] 2016-01-25 21:33
@dragGH102 thanks for the help. Seems I mislead you though,

I was having a different issue. The end message was the same (Unable to start activity) but the actual issue was different. Sorry for the confusion

**Comment by ginev** [comment] 2016-02-02 07:43
@Ivshti @dragGH102  I assume you have worked around the issues you were experiencing? I am closing the thread. Feel free to reopen it if needed.

**Closed by ginev** 2016-02-02 07:43 UTC
Labels: help wanted

**Comment by Ivshti** [comment] 2016-02-02 08:05
@ginev I had to install android sdk 23 and it worked. thanks

**Comment by dragGH102** [comment] 2016-02-02 12:18
@lvshti thank you for your follow up.
actually I just left it behind in favor of the core list view.

however, for the records, as outlined by others (see above) Apparently it
was depending on the wrong installed or configured sdk. even though it's
strange because RadSideDrawer doesn't give such issue

**Comment by Ivshti** [comment] 2016-02-02 12:22
@dragGH102 I am also considering pure ListView, since I'm seeing some issues with RadListView. However, core selling point for me is load on demand, and I'm not sure if ListView can do that

**Comment by ginev** [comment] 2016-02-02 12:52
@Ivshti can you please open a new issue regarding the RadListView issues? We will take a look and try to get them solved as soon as possible.

**Comment by Ivshti** [comment] 2016-02-02 12:56
@ginev sure. It's a bit difficult describing them in a technical manner though, and some of them seem by design - for example data binding does not work on the layout element

**Comment by ginev** [comment] 2016-02-02 14:44
@Ivshti With "layout element" you mean the `ListViewLinearLayout` or `ListViewGridLayout` objects you are setting to the `listViewLayout` property?

**Comment by Ivshti** [comment] 2016-02-02 15:42
@ginev yes. Currently I've implemented a watcher on property changes which create new ``ListViewGridLayout`` and assigns it as a layout

**Comment by dragGH102** [comment] 2016-02-02 18:29
>
> However, core selling point for me is load on demand, and I'm not sure if
> ListView can do that


@Ivo I believe the load on demand can be done programatically onload (or
with a custom watcher like you mentioned in a later comment) most times

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by liverbool** [comment] 2016-06-06 10:38
Hi,Guys

I got same error

```shell
Jun  6 17:34:57 Ishmael appregist[83240]: file:///app/tns_modules/ui/builder/builder.js:156:56: JS ERROR Error: Building UI from XML. @file:///app/views/member/member.xml:25:9
	 ↳Module '/Users/dos/Library/Developer/CoreSimulator/Devices/E2EE7727-E7DC-4101-8F3A-C9EE89F69560/data/Containers/Bundle/Application/9838F6C2-29D9-489B-B322-B153A3B3EC23/appregist.app/app/tns_modules/nativescript-telerik-ui/listview' not found for element 'nativescript-telerik-ui/listview:RadListView'.
	   ↳Can't find variable: TKListViewDelegate
Jun  6 17:34:57 Ishmael com.apple.CoreSimulator.SimDevice.E2EE7727-E7DC-4101-8F3A-C9EE89F69560.launchd_sim[76568] (UIKitApplication:org.nativescript.appregist[0xeb62][83240]): Service exited due to signal: Segmentation fault: 11
```

**My XML**

```xml
<Page
    xmlns:lv="nativescript-telerik-ui/listview" 
    xmlns="http://schemas.nativescript.org/tns.xsd"
    navigatingTo="navigatingTo"
    >
    <ActionBar title="Members">
        <ActionBar.actionItems>
            <ActionItem tap="addNewMember" ios.position="right" ios.systemIcon="4" android.systemIcon="ic_menu_add" />
        </ActionBar.actionItems>
    </ActionBar>

  <GridLayout orientation="vertical" rows="auto, *">
     <!-- >> listview-pull-to-refresh-xml -->
        <lv:RadListView items="{{ items }}" pullToRefresh="true" row="1" pullToRefreshInitiated="{{onPullToRefreshInitiated}}">
     <!-- << listview-pull-to-refresh-xml -->
            <lv:RadListView.listViewLayout>
                <lv:ListViewLinearLayout scrollDirection="Vertical"/>
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
              <Label text="{{ name }}" marginBottom="8" />
            </lv:RadListView.itemTemplate>
        </lv:RadListView>
    </GridLayout>
</Page>

```

**My Steps**

```shell
$ tns plugin add nativescript-telerik-ui
$ tns livesync ios --emulator --watch
```

**Comment by ginev** [comment] 2016-06-09 15:25
@liverbool, can you try tns prepare ios and tns run ios instead of livesync?

**Comment by depsimon** [comment] 2016-06-16 16:03
Thanks @ginev I don't know why but this seemed to do the trick. 
I had the same issue and now it's working !

**Comment by Mohamed-Fakhry** [comment] 2016-12-27 15:35
@dragGH102 
missed lv
`
<Page loaded="loaded" xmlns:lv="nativescript-telerik-ui/listview" xmlns="http://www.nativescript.org/tns.xsd">
         <lv:RadListView>
        </lv:RadListView>
</Page>
`
