### ISSUE TITLE
Hardcoded paths getting into project.pbxproj

### ISSUE THREAD

**Issue by maknz** [telerik/nativescript-ui-samples#8] opened 2015-08-06 22:34 UTC
We noticed that when we installed the new {N} Telerik UI, that hardcoded paths were being added to the project.pbxproj file. [This file must be kept in version control](http://stackoverflow.com/questions/8026429/should-i-git-ignore-xcodeproject-project-pbxproj-file). Therefore, whenever someone builds the project, there are always changes to this file or path errors. Is this something that can be fixed as the releases progress?

We are keeping the iOS platform in version control because we use Cocoapods. Once we have proper support for pods, we can un-ignore the platform and generate for everyone. Since the platform is normally ignored, I can see how this won't be a problem for people not using Pods / any other reason to have the platform checked in.

**Comment by PanayotCankov** [comment] 2015-08-07 08:03
You are absolutely right. Ultimately everything for your project will be declared in the package.json or kept in app/App_Resources and the `platforms` folder should not be kept under source control. The CLI should be used to create a valid Xcode project in `platforms/ios` out of these settings and source files.

The vanguard of {N} however need to keep the `platforms` in source control due to using some features that are supported by the runtimes but the tooling around them is not done yet. Besides the Cocoapods (support for which is planned for 1.3.0) I can think of using iOS Extensions. With some of our examples we managed to do a search and replace in the Xcode project, replacing paths such as `/Users/cankov/Projects/ShareTarget/platforms/ios/` to `../../` and it worked, it was round-tripping through source control. This was fixing paths in various linker flags.

I hope a similar approach will help you out.

**Comment by maknz** [comment] 2015-08-09 22:58
Cool. Yeah, another reason to have the project committed is for iOS splash screens on app launch. So it seems like we'll probably have to have the project committed for a long time. The `../../` path fix could be adequate, so long as that change won't get bowled over with absolute paths in the future. Something to play with anyway, or ideally have the problem fixed at the root :+1:

**Comment by maknz** [comment] 2015-08-10 03:29
Every time the project is prepared, the pbxproj file gets overwritten with hardcoded paths again. Ugh. Hopefully https://github.com/NativeScript/nativescript-cli/issues/759 won't be far away.

**Comment by teobugslayer** [comment] 2015-08-10 10:15
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/679 - Please check once we release 1.2.2

**Closed by teobugslayer** 2015-08-10 10:15 UTC
