### ISSUE TITLE
I wonder when RadListView will be ready for production

### ISSUE THREAD

**Issue by alexrainman** [telerik/nativescript-ui-samples#57] opened 2016-02-05 00:54 UTC
It's the only thing stopping me to move forward with {N}. And, add Grouping functionality, please?

**Comment by ginev** [comment] 2016-02-05 08:32
Hello @alexrainman ,

Grouping is on our TODO list and will be available very soon. 
Are you having other show-stopper issues with RadListView that need immediate attention?

**Comment by alexrainman** [comment] 2016-02-05 13:59
Yes, swipe actions are not working well. On iOS they don't expand to text size and in Android when you swipe, both left and right buttons are visible but only right one is clickable. It crash too on pull to refresh and load more but i need to test a bit more.

**Comment by alexrainman** [comment] 2016-02-05 14:28
<img width="390" alt="screen shot 2016-02-05 at 8 28 09 am" src="https://cloud.githubusercontent.com/assets/3793554/12848949/724c4fa2-cbe2-11e5-81fa-14c35cca3733.png">

**Comment by alexrainman** [comment] 2016-02-05 14:43
And load more Manual mode button height looks like this:

<img width="376" alt="screen shot 2016-02-05 at 8 42 31 am" src="https://cloud.githubusercontent.com/assets/3793554/12849280/7cb13406-cbe4-11e5-96ab-8a70ab8d20d0.png">

**Comment by ginev** [comment] 2016-02-08 08:30
Hello @alexrainman ,

1. The issue with the big load-on-demand button is already addressed in our internal codebase.
2. The Swipe-to-execute behavior you are seeing on iOS is probably due to missing backgroundColor on the main item. You need to set it and the buttons below will be covered as expected.
3. The Android issue with not being able to click on the item is not reproducible here - can you paste some code for verification? This is also applicable to the errors with pull-to-refresh - any code snippets that we could use to reproduce them will be very useful. Thanks!

**Closed** 2016-02-22 08:04 UTC
Labels: question
